---
apiVersion: v1
kind: ConfigMap
metadata:
  name: empleo-cv-config
data:
  NODE_ENV: "{{ .Values.node.env }}"

  # Authentication
  # --------------
  # These two values come from the global redis config map
  #  REDIS_HOST: "{{ .Values.redis.host }}"
  #  REDIS_PORT: "{{ .Values.redis.port }}"
  REDIS_DATABASE: "{{ .Values.redis.database }}"
  REDIS_KEY_PREFIX: "{{ .Values.redis.keyPrefix }}"
  KEYCLOAK_ISSUER: "{{ .Values.keycloak.issuer }}"
  PROFILE_SVC_URI: "{{ .Values.apiManager.profileSvcUri }}"

  # CV
  # --
  POSTGRES_URI: "postgres://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}"

