---
apiVersion: v1
kind: ConfigMap
metadata:
  name: empleo-cv-svc
data:
  NODE_ENV: "{{ .Values.node.env }}"

  KEYCLOAK_REALM: "{{ .Values.keycloak.realm }}"
  KEYCLOAK_USER_MANAGEMENT_SERVICE_URI: "{{ .Values.apiManager.uri }}/coreplatform-keycloak-user-mgmt"
  KEYCLOAK_ISSUER: "{{ .Values.keycloak.issuer }}"
  POSTGRES_URI: "postgres://{{ .Values.postgres.cv_microservice }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}"

  # These two values come from the global redis config map
  #  REDIS_HOST: "{{ .Values.redis.host }}"
  #  REDIS_PORT: "{{ .Values.redis.port }}"
  REDIS_DATABASE: "{{ .Values.redis.database }}"
  REDIS_KEY_PREFIX: "{{ .Values.redis.keyPrefix }}"
