apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name | trunc 63 }}
  labels:
    app: {{ .Chart.Name | trunc 63 }}
  annotations:
{{- with .Values.service.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name | trunc 63 }}
  ports:
  {{- range $key, $value := .Values.service.ports }}
    - name: {{ $key }}
{{ toYaml $value | indent 6 }}
  {{- end }}