version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: cv_microservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwd
    ports:
      - 5432:5432
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
