## DEFAULTS VALUES FOR SVC
service:
  type: ClusterIP
  ports:
    http:
      port: 3000
      targetPort: 3000
      protocol: TCP
    debug:
      port: 9229
      targetPort: 9229
      protocol: TCP

## DEFAULTS VALUES FOR DEPLOYMENTS
container:
  ports:
    http:
      containerPort: 3000
      protocol: TCP
    debug:
      containerPort: 9229
      protocol: TCP

replicaCount: 1
updateStrategy:
  type: RollingUpdate
image:
  ##This value always rewrite in the deployment
  repository: {}
  tag: {}
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  tcpSocket:
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 30
  # periodSeconds: 30
  # timeoutSeconds: 30
  # failureThreshold: 6
  # successThreshold: 1

readinessProbe:
  tcpSocket:
    port: 3000
  initialDelaySeconds: 20
  periodSeconds: 20
  # periodSeconds: 30
  # timeoutSeconds: 30
  # failureThreshold: 6
  # successThreshold: 1

nodeSelector: {}

tolerations: []

podAnnotations: {}
  # iam.amazonaws.com/role: "logstash-role"
  # prometheus.io/scrape: "true"
  # prometheus.io/path: "/metrics"
  # prometheus.io/port: "9198"
